version: "3.9"

services:
  spark-master:
    image: apache/spark:3.5.1-python3
    container_name: spark-master
    hostname: spark-master
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.master.Master",
        "--host",
        "spark-master",
        "--port",
        "7077",
        "--webui-port",
        "8080",
      ]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=python3
    ports:
      - "8080:8080" # UI Master
      - "7077:7077" # Cluster Spark

  spark-worker:
    image: apache/spark:3.5.1-python3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=python3
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    command:
      [
        "/opt/spark/bin/spark-class",
        "org.apache.spark.deploy.worker.Worker",
        "spark://spark-master:7077",
        "--webui-port",
        "8081",
      ]
    ports:
      - "8081:8081" # UI Worker (useful for debugging)
    networks: [spark-network]

  spark-connect:
    build:
      context: https://github.com/francescor-tuidi/spark-docker-setup.git#main
      dockerfile: Dockerfile
    container_name: spark-connect
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
    depends_on:
      - spark-master
    ports:
      - "15002:15002"
    networks:
      - spark-network

networks:
  spark-network:
    driver: bridge
